In [2]:
import tensorflow as tf
data1=tf.placeholder(tf.float32)
data2=tf.placeholder(tf.float32)
dataADD=tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataADD,feed_dict={data1:6,data2:2}))
    #1 dataADD 2 需要追加的数据，语法：(feed_dict={1:,2:})

8.0


In [15]:
#矩阵类比为M×N的数组 [],首先写一个[],[]里面的[]数表明行数，填写数据表明列数
import tensorflow as tf
data1=tf.constant([[6,6]])
data2=tf.constant([[2],
                   [2]])
data3=tf.constant([[3,3]])
data4=tf.constant([[1,2],
                   [3,4],
                   [5,6]])
print(data4.shape)#读取维度
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[0]))#打印行
    print(sess.run(data4[:,0]))#打印列
    print(sess.run(data4[0,0]))#打印单个位置
    print(sess.run(data4[0:2,1]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1
[2 4]


In [18]:
import tensorflow as tf
data1=tf.constant([[6,6]])
data2=tf.constant([[2],
                   [2]])
data3=tf.constant([[3,3]])
data4=tf.constant([[1,2],
                   [3,4],
                   [5,6]])
matMul=tf.matmul(data1,data2)
matAdd=tf.add(data1,data3)
matMul2=tf.multiply(data1,data3)#对应元素相乘
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))
    print(sess.run(matMul2))
    print(sess.run([matMul,matMul2]))#打印多个结果
print('end!')

[[24]]
[[9 9]]
[[18 18]]
[array([[24]]), array([[18, 18]])]
end!


In [23]:
#特殊矩阵初始化
import tensorflow as tf
mat0=tf.constant([[0,0,0],
                 [0,0,0]])
mat1=tf.zeros([2,3])#空矩阵
mat2=tf.ones([2,3])#全1矩阵
mat3=tf.fill([2,3],15)#填充矩阵
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))
print('end!')    

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[15 15 15]
 [15 15 15]]
end!


In [28]:
import tensorflow as tf
mat0=tf.constant([[2],
                  [3],
                  [4]])
mat1=tf.zeros_like(mat0)#相同维度全0矩阵
mat2=tf.linspace(0.0,2.0,11)#等距划分
mat3=tf.random_uniform([2,3],-1,2)#随机矩阵 1 大小 2 最小 3 最大
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[1.2574701  1.2026248  0.06965244]
 [0.9787611  0.5183581  1.7777085 ]]
